trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - src/**

jobs:
- job: ASPNETCore
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: '--configuration Release -p:SourceRevisionId=$(Build.SourceVersion)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--configuration Release --no-build --settings src/moonglade.runsettings --collect "Code coverage" -- RunConfiguration.DisableAppDomain=true'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration Release -p:SourceRevisionId=$(Build.SourceVersion) --no-build --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: Copy to Drop
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'Drop'
